name: Push the container image

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

env:
  CONTAINER_REGISTRY: ghcr.io

jobs:
  push_image:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Calculate the version
        run: echo "IMAGE_VERSION=$(git describe --tags --always)" >> $GITHUB_ENV
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push mysql
        uses: docker/build-push-action@v5
        with:
          context: ./containers/mysql
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ env.CONTAINER_REGISTRY }}/${{ github.repository }}-mysql:v0.1.0
      - name: Build and push migrator
        uses: docker/build-push-action@v5
        with:
          context: ./containers/migrator
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ env.CONTAINER_REGISTRY }}/${{ github.repository }}-migrator:v0.1.0
      - name: Build and push api
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./containers/api/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ env.CONTAINER_REGISTRY }}/${{ github.repository }}-api:v0.1.0
      - name: Slim build and push api
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./containers/api/Dockerfile.slim
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ env.CONTAINER_REGISTRY }}/${{ github.repository }}-api:v0.1.0
      - name: Build and push web
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./containers/web/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ env.CONTAINER_REGISTRY }}/${{ github.repository }}-web:v0.1.0
      - name: Slim build and push web
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./containers/web/Dockerfile.slim
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ env.CONTAINER_REGISTRY }}/${{ github.repository }}-web:v0.1.0
      - name: Build and push nginx-api
        uses: docker/build-push-action@v5
        with:
          context: ./containers/nginx-api
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ env.CONTAINER_REGISTRY }}/${{ github.repository }}-nginx-api:v0.1.0
      - name: Build and push nginx-web
        uses: docker/build-push-action@v5
        with:
          context: ./containers/nginx-web
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ env.CONTAINER_REGISTRY }}/${{ github.repository }}-nginx-web:${{ env.IMAGE_VERSION }}
